---
name: EmoteCommands
version: 1.0.0
main: DiamondStrider1\EmoteCommands\Loader
api: 4.0.0

permissions:
  emotecommands.admin:
    default: op
    description: Manage EmoteCommands Plugin
  emotecommands.admin.create:
    default: op
    description: Create new EmoteCommands
  emotecommands.admin.edit:
    default: op
    description: Edit existing EmoteCommands
  emotecommands.admin.remove:
    default: op
    description: Remove existing EmoteCommands
